CREATE TABLE IF NOT EXISTS artists (
    artist_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    artist_name TEXT NOT NULL,
    location TEXT NOT NULL,
    genre TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username TEXT NOT NULL UNIQUE,
    location TEXT NOT NULL,
    user_email TEXT NOT NULL,
    user_password TEXT NOT NULL,
    user_fullname TEXT NOT NULL,
    artist BOOLEAN NOT NULL,
    nickname TEXT
);

-- psql -U vctrjrvs -d chorum-db -f ./sql-scripts/seed.users.sql
